create user ABABEI identified by ABABEI quota 10M on paraotros;
grant connect, resource to ABABEI;
create user BLANCO identified by BLANCO quota 10M on paraotros;
grant connect, resource to BLANCO;
create user CASTELLANO identified by CASTELLANO quota 10M on paraotros;
grant connect, resource to CASTELLANO;
create user CIOBANU identified by CIOBANU quota 10M on paraotros;
grant connect, resource to CIOBANU;
create user COBERTERA identified by COBERTERA quota 10M on paraotros;
grant connect, resource to COBERTERA;
create user CONDORI identified by CONDORI quota 10M on paraotros;
grant connect, resource to CONDORI;
create user CONTONENTE identified by CONTONENTE quota 10M on paraotros;
grant connect, resource to CONTONENTE;
create user CRUZ identified by CRUZ quota 10M on paraotros;
grant connect, resource to CRUZ;
create user FERNANDO identified by FERNANDO quota 10M on paraotros;
grant connect, resource to FERNANDO;
create user GONZALEZ identified by GONZALEZ quota 10M on paraotros;
grant connect, resource to GONZALEZ;
create user LOPEZ identified by LOPEZ quota 10M on paraotros;
grant connect, resource to LOPEZ;
create user MARTINEZ identified by MARTINEZ quota 10M on paraotros;
grant connect, resource to MARTINEZ;
create user MBA identified by MBA quota 10M on paraotros;
grant connect, resource to MBA;
create user RAMOS identified by RAMOS quota 10M on paraotros;
grant connect, resource to RAMOS;
create user RANERA identified by RANERA quota 10M on paraotros;
grant connect, resource to RANERA;
create user ROLLAN identified by ROLLAN quota 10M on paraotros;
grant connect, resource to ROLLAN;
create user SIMON identified by SIMON quota 10M on paraotros;
grant connect, resource to SIMON;
create user UTRERO identified by UTRERO quota 10M on paraotros;
grant connect, resource to UTRERO;
create user VILLARTA identified by VILLARTA quota 10M on paraotros;
grant connect, resource to VILLARTA;
create user YUBERO identified by YUBERO quota 10M on paraotros;
grant connect, resource to YUBERO;
create user PROFESOR identified by PROFESOR quota 10M on paraotros;
grant connect, resource to PROFESOR;
create user BERMUDEZ identified by BERMUDEZ51 quota unlimited on Users;
grant connect, resource to BERMUDEZ;
