create user PRUEBAS identified by PRUEBAS quota 10M on paraotros default tablespace paraotros;
grant connect, resource to PRUEBAS;
grant connect, resource to BERMUDEZ;
create user ABABEI identified by ABABEI quota 10M on paraotros default tablespace paraotros;
grant connect, resource to ABABEI;
grant connect, resource to BERMUDEZ;
create user BLANCO identified by BLANCO quota 10M on paraotros default tablespace paraotros;
grant connect, resource to BLANCO;
grant connect, resource to BERMUDEZ;
create user CASTELLANO identified by CASTELLANO quota 10M on paraotros default tablespace paraotros;
grant connect, resource to CASTELLANO;
grant connect, resource to BERMUDEZ;
create user CIOBANU identified by CIOBANU quota 10M on paraotros default tablespace paraotros;
grant connect, resource to CIOBANU;
grant connect, resource to BERMUDEZ;
create user COBERTERA identified by COBERTERA quota 10M on paraotros default tablespace paraotros;
grant connect, resource to COBERTERA;
grant connect, resource to BERMUDEZ;
create user CONDORI identified by CONDORI quota 10M on paraotros default tablespace paraotros;
grant connect, resource to CONDORI;
grant connect, resource to BERMUDEZ;
create user CONTONENTE identified by CONTONENTE quota 10M on paraotros default tablespace paraotros;
grant connect, resource to CONTONENTE;
grant connect, resource to BERMUDEZ;
create user CONDORI identified by CONDORI quota 10M on paraotros default tablespace paraotros;
grant connect, resource to CONDORI;
grant connect, resource to BERMUDEZ;
create user CRUZ identified by CRUZ quota 10M on paraotros default tablespace paraotros;
grant connect, resource to CRUZ;
grant connect, resource to BERMUDEZ;
create user FERNANDEZ identified by FERNANDEZ quota 10M on paraotros default tablespace paraotros;
grant connect, resource to FERNANDEZ;
grant connect, resource to BERMUDEZ;
create user GONZALEZ identified by GONZALEZ quota 10M on paraotros default tablespace paraotros;
grant connect, resource to GONZALEZ;
grant connect, resource to BERMUDEZ;
create user LOPEZ identified by LOPEZ quota 10M on paraotros default tablespace paraotros;
grant connect, resource to LOPEZ;
grant connect, resource to BERMUDEZ;
create user MARTINEZ identified by MARTINEZ quota 10M on paraotros default tablespace paraotros;
grant connect, resource to MARTINEZ;
grant connect, resource to BERMUDEZ;
create user MBA identified by MBA quota 10M on paraotros default tablespace paraotros;
grant connect, resource to MBA;
grant connect, resource to BERMUDEZ;
create user RAMOS identified by RAMOS quota 10M on paraotros default tablespace paraotros;
grant connect, resource to RAMOS;
grant connect, resource to BERMUDEZ;
create user RANERA identified by RANERA quota 10M on paraotros default tablespace paraotros;
grant connect, resource to RANERA;
grant connect, resource to BERMUDEZ;
create user ROLLAN identified by ROLLAN quota 10M on paraotros default tablespace paraotros;
grant connect, resource to ROLLAN;
grant connect, resource to BERMUDEZ;
create user SIMON identified by SIMON quota 10M on paraotros default tablespace paraotros;
grant connect, resource to SIMON;
grant connect, resource to BERMUDEZ;
create user UTRERO identified by UTRERO quota 10M on paraotros default tablespace paraotros;
grant connect, resource to UTRERO;
grant connect, resource to BERMUDEZ;
create user VILLARTA identified by VILLARTA quota 10M on paraotros default tablespace paraotros;
grant connect, resource to VILLARTA;
grant connect, resource to BERMUDEZ;
create user YUBERO identified by YUBERO quota 10M on paraotros default tablespace paraotros;
grant connect, resource to YUBERO;
grant connect, resource to BERMUDEZ;
create user PROFESOR identified by PROFESOR quota 10M on paraotros default tablespace paraotros;
grant connect, resource to PROFESOR;
grant connect, resource to BERMUDEZ;
create user BERMUDEZ identified by BERMUDEZ51 default tablespace USERS quota unlimited on Users;
grant connect, resource to BERMUDEZ;
